from flask import Flask, request, send_file, render_template, jsonify, send_from_directory
from groq import Groq
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import json, io, os, uuid

app = Flask(__name__)

# ─── CONFIG ───────────────────────────────────────────────
API_KEY = os.getenv("GROQ_API_KEY")
SITES_FOLDER = os.path.join(os.path.dirname(__file__), "generated_sites")
os.makedirs(SITES_FOLDER, exist_ok=True)
# ──────────────────────────────────────────────────────────

SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)

C_BG_DARK   = RGBColor(0x0A, 0x0A, 0x18)
C_BG_MID    = RGBColor(0x10, 0x10, 0x28)
C_BG_LIGHT  = RGBColor(0xF0, 0xF2, 0xFF)
C_PANEL     = RGBColor(0x14, 0x14, 0x30)
C_ACCENT1   = RGBColor(0x7C, 0x3A, 0xFF)
C_ACCENT2   = RGBColor(0x00, 0xD4, 0xFF)
C_ACCENT3   = RGBColor(0xFF, 0x6B, 0x35)
C_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)
C_TEXT_DARK = RGBColor(0x12, 0x12, 0x2A)
C_MUTED     = RGBColor(0x88, 0x88, 0xAA)

def rgb(r, g, b): return RGBColor(r, g, b)

def add_rect(slide, x, y, w, h, fill_color, line_color=None):
    shape = slide.shapes.add_shape(1, Inches(x), Inches(y), Inches(w), Inches(h))
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    if line_color:
        shape.line.color.rgb = line_color
        shape.line.width = Pt(1)
    else:
        shape.line.fill.background()
    return shape

def add_textbox(slide, x, y, w, h, text, font_size, bold=False,
                color=C_WHITE, align=PP_ALIGN.LEFT, italic=False, font_name="Calibri"):
    txb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = txb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name = font_name
    return txb

def dark_bg(slide):
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = C_BG_DARK

def light_bg(slide):
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = C_BG_LIGHT

def add_slide_number(slide, num):
    add_textbox(slide, 12.5, 7.1, 0.7, 0.3, str(num), 9, color=C_MUTED, align=PP_ALIGN.RIGHT)

def build_title_slide(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); dark_bg(slide)
    add_rect(slide, 9.5, -0.5, 5, 5, C_ACCENT1)
    add_rect(slide, 10.2, -0.3, 5, 5, C_BG_DARK)
    add_rect(slide, 0, 6.9, 13.33, 0.6, C_ACCENT1)
    add_rect(slide, 0, 0, 0.22, 7.5, C_ACCENT2)
    add_textbox(slide, 0.6, 1.8, 10, 1.6, data["title"], 52, bold=True, color=C_WHITE)
    if data.get("explanation"):
        add_textbox(slide, 0.6, 3.6, 9, 1.0, data["explanation"], 18, color=rgb(0xBB,0xBB,0xDD))
    add_textbox(slide, 0.6, 7.0, 8, 0.4, "Generated by PPTFinders AI", 11, color=C_WHITE)

def build_two_column_slide(prs, data, slide_num):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); light_bg(slide)
    add_rect(slide, 0, 0, 5.5, 7.5, C_BG_MID)
    add_rect(slide, 0, 0, 5.5, 0.18, C_ACCENT1)
    add_textbox(slide, 0.35, 0.45, 4.8, 1.4, data["title"], 26, bold=True, color=C_WHITE)
    if data.get("explanation"):
        add_textbox(slide, 0.35, 2.0, 4.7, 4.8, data["explanation"], 13.5, color=rgb(0xCC,0xCC,0xEE))
    bullets = data.get("bullets", []); card_y = 0.5
    for i, bullet in enumerate(bullets[:5]):
        cc = [C_ACCENT1,C_ACCENT2,rgb(0x28,0x28,0x50),rgb(0x00,0x90,0xB0),rgb(0x55,0x20,0xCC)][i%5]
        add_rect(slide, 5.8, card_y, 7.1, 1.1, rgb(0xFF,0xFF,0xFF))
        add_rect(slide, 5.8, card_y, 0.12, 1.1, cc)
        add_rect(slide, 6.05, card_y+0.22, 0.6, 0.6, cc)
        add_textbox(slide, 6.05, card_y+0.22, 0.6, 0.6, str(i+1), 14, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
        add_textbox(slide, 6.85, card_y+0.12, 5.9, 0.88, bullet, 13, color=C_TEXT_DARK)
        card_y += 1.22
    add_slide_number(slide, slide_num)

def build_fulltext_slide(prs, data, slide_num):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); dark_bg(slide)
    add_rect(slide, 0, 0, 13.33, 0.14, C_ACCENT2)
    add_rect(slide, 11.8, 0.14, 1.53, 7.36, C_PANEL)
    add_textbox(slide, 0.5, 0.3, 11.0, 0.9, data["title"], 30, bold=True, color=C_WHITE)
    if data.get("explanation"):
        add_textbox(slide, 0.5, 1.4, 10.9, 2.6, data["explanation"], 15, color=rgb(0xCC,0xCC,0xEE))
    bullets = data.get("bullets", [])
    if bullets:
        add_rect(slide, 0, 4.3, 13.33, 0.04, C_ACCENT1)
        add_textbox(slide, 0.5, 4.45, 4, 0.35, "KEY POINTS", 9, bold=True, color=C_ACCENT2)
        col_x = [0.5, 4.0, 7.5]
        for i, bullet in enumerate(bullets[:3]):
            cx = col_x[i%3]
            add_rect(slide, cx, 4.95, 3.2, 2.2, C_PANEL)
            add_rect(slide, cx, 4.95, 3.2, 0.1, C_ACCENT1)
            add_textbox(slide, cx+0.15, 5.15, 2.9, 1.95, bullet, 12.5, color=C_WHITE)
    add_slide_number(slide, slide_num)

def build_stat_callout_slide(prs, data, slide_num):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); light_bg(slide)
    add_rect(slide, 0, 0, 0.22, 7.5, C_ACCENT1)
    add_rect(slide, 0.22, 0, 13.11, 1.3, C_BG_MID)
    add_textbox(slide, 0.55, 0.2, 11, 0.9, data["title"], 28, bold=True, color=C_WHITE)
    if data.get("explanation"):
        add_textbox(slide, 0.5, 1.5, 8.3, 2.3, data["explanation"], 14, color=C_TEXT_DARK)
    bullets = data.get("bullets", []); box_y = 1.45
    for i, bullet in enumerate(bullets[:4]):
        c = [C_ACCENT1,C_ACCENT2,C_ACCENT3,rgb(0x28,0x9B,0x6C)][i%4]
        add_rect(slide, 9.1, box_y, 3.9, 1.35, c)
        add_textbox(slide, 9.2, box_y+0.05, 0.7, 0.55, f"0{i+1}", 22, bold=True, color=rgb(0xFF,0xFF,0xFF))
        add_textbox(slide, 9.2, box_y+0.5, 3.6, 0.85, bullet, 12, color=C_WHITE)
        box_y += 1.45
    add_slide_number(slide, slide_num)

def build_timeline_slide(prs, data, slide_num):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); dark_bg(slide)
    add_rect(slide, 0, 0, 13.33, 0.14, C_ACCENT1)
    add_textbox(slide, 0.5, 0.3, 12, 0.9, data["title"], 30, bold=True, color=C_WHITE)
    if data.get("explanation"):
        add_textbox(slide, 0.5, 1.3, 12.3, 1.1, data["explanation"], 14, color=rgb(0xBB,0xBB,0xDD))
    add_rect(slide, 0.5, 3.1, 12.3, 0.08, C_ACCENT2)
    bullets = data.get("bullets", [])
    step_w = 12.3 / max(len(bullets), 1)
    for i, bullet in enumerate(bullets[:5]):
        cx = 0.5 + i*step_w + step_w/2 - 0.3
        add_rect(slide, cx, 2.82, 0.6, 0.6, C_ACCENT1)
        add_textbox(slide, cx, 2.82, 0.6, 0.6, str(i+1), 14, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
        add_rect(slide, cx-0.5, 3.4, 1.6, 2.8, C_PANEL)
        add_textbox(slide, cx-0.4, 3.5, 1.5, 2.7, bullet, 11.5, color=C_WHITE)
    add_slide_number(slide, slide_num)

def build_grid_slide(prs, data, slide_num):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); light_bg(slide)
    add_rect(slide, 0, 0, 13.33, 1.25, C_BG_MID)
    add_rect(slide, 0, 0, 0.22, 7.5, C_ACCENT2)
    add_textbox(slide, 0.5, 0.2, 12, 0.85, data["title"], 28, bold=True, color=C_WHITE)
    bullets = data.get("bullets", [])
    positions = [(0.4,1.45),(4.55,1.45),(8.7,1.45),(0.4,4.0),(4.55,4.0),(8.7,4.0)]
    accents = [C_ACCENT1,C_ACCENT2,C_ACCENT3,rgb(0x28,0x9B,0x6C),rgb(0xE0,0x60,0x20),rgb(0x44,0x44,0xCC)]
    for i, bullet in enumerate(bullets[:6]):
        if i >= len(positions): break
        px, py = positions[i]; ac = accents[i%len(accents)]
        add_rect(slide, px+0.05, py+0.05, 3.8, 2.3, rgb(0xDD,0xDD,0xEE))
        add_rect(slide, px, py, 3.8, 2.3, C_WHITE)
        add_rect(slide, px, py, 3.8, 0.22, ac)
        add_rect(slide, px+0.12, py+0.35, 0.55, 0.55, ac)
        add_textbox(slide, px+0.12, py+0.35, 0.55, 0.55, str(i+1), 14, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
        add_textbox(slide, px+0.8, py+0.3, 2.85, 1.85, bullet, 12, color=C_TEXT_DARK)
    add_slide_number(slide, slide_num)

def build_conclusion_slide(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6]); dark_bg(slide)
    add_rect(slide, 0, 0, 13.33, 0.14, C_ACCENT2)
    add_rect(slide, 0, 7.36, 13.33, 0.14, C_ACCENT1)
    add_rect(slide, 0, 0, 0.22, 7.5, C_ACCENT1)
    add_textbox(slide, 1.5, 1.6, 10.3, 1.4, data["title"], 46, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
    if data.get("explanation"):
        add_textbox(slide, 1.5, 3.2, 10.3, 1.5, data["explanation"], 16, color=rgb(0xBB,0xBB,0xDD), align=PP_ALIGN.CENTER)
    bullets = data.get("bullets", [])
    if bullets:
        bx = 2.5
        for b in bullets[:3]:
            add_textbox(slide, bx, 5.1, 3.0, 0.55, f"✦  {b}", 13, color=C_ACCENT2, align=PP_ALIGN.CENTER)
            bx += 3.0
    add_textbox(slide, 0.5, 6.95, 8, 0.45, "Generated by PPTFinders AI", 11, color=C_MUTED)

LAYOUT_CYCLE = [
    "two_column","fulltext","stat_callout","two_column","timeline",
    "grid","fulltext","stat_callout","two_column","grid","timeline",
    "fulltext","stat_callout","grid","two_column","timeline","fulltext",
    "grid","stat_callout","two_column",
]

def build_pptx(slides_data):
    prs = Presentation()
    prs.slide_width = SLIDE_W; prs.slide_height = SLIDE_H
    slide_num = 1
    for i, sd in enumerate(slides_data):
        stype = sd.get("slide_type", "content")
        if stype == "title": build_title_slide(prs, sd)
        elif stype == "conclusion": build_conclusion_slide(prs, sd)
        else:
            layout = LAYOUT_CYCLE[(i-1) % len(LAYOUT_CYCLE)]
            if layout == "two_column": build_two_column_slide(prs, sd, slide_num)
            elif layout == "fulltext": build_fulltext_slide(prs, sd, slide_num)
            elif layout == "stat_callout": build_stat_callout_slide(prs, sd, slide_num)
            elif layout == "timeline": build_timeline_slide(prs, sd, slide_num)
            elif layout == "grid": build_grid_slide(prs, sd, slide_num)
            slide_num += 1
    buf = io.BytesIO(); prs.save(buf); buf.seek(0)
    return buf.read()

def generate_slide_content(user_prompt, num_slides):
    client = Groq(api_key=API_KEY)
    num_slides = max(5, min(30, num_slides))
    content_slides = num_slides - 2
    system_prompt = f"""You are an expert presentation designer and content writer.
Return ONLY a valid JSON array of exactly {num_slides} slides. No markdown, no backticks, no extra text.
Each slide: "title" (max 8 words), "slide_type" (title|content|conclusion),
"explanation" (3-5 professional sentences), "bullets" (4-6 short phrases).
Slide 1=title, Slide {num_slides}=conclusion, rest=content ({content_slides} content slides, each different aspect).
Return ONLY raw JSON array."""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role":"system","content":system_prompt},
                  {"role":"user","content":f"Create a {num_slides}-slide presentation about: {user_prompt}"}],
        temperature=0.65, max_tokens=8000,
    )
    raw = response.choices[0].message.content.strip()
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"): raw = raw[4:]
    raw = raw.strip()
    slides = json.loads(raw)
    if slides: slides[0]["slide_type"]="title"; slides[-1]["slide_type"]="conclusion"
    return slides


# ═════════════════════════════════════════════════════════
# WEBSITE GENERATOR
# ═════════════════════════════════════════════════════════

def generate_website_code(user_prompt: str) -> str:
    client = Groq(api_key=API_KEY)

    system_prompt = """You are an elite full-stack web developer and UI/UX designer.
When given a website description, generate a COMPLETE, beautiful, single-file HTML website.

STRICT RULES — follow exactly:
1. Return ONLY raw HTML code starting with <!DOCTYPE html>. No explanation, no markdown, no backticks.
2. All CSS must be inside a <style> tag in <head>
3. All JavaScript must be inside a <script> tag before </body>
4. Must be a fully working standalone file — no external dependencies except Google Fonts CDN
5. Must include ALL of these sections:
   - Sticky navigation bar with logo/brand name and smooth scroll links
   - Hero section: big headline, subheadline, 1-2 CTA buttons, background visual
   - Features/Services section: 3-6 cards in a grid with icons (use emoji or CSS shapes)
   - About or How It Works section
   - Stats/Numbers section with impressive figures relevant to the topic
   - Testimonials section with 3 fake but realistic reviews
   - Contact form section (name, email, message fields — no backend needed)
   - Footer with links and copyright

DESIGN RULES:
- Pick a bold color palette that fits the topic (NOT generic blue/white)
- Use Google Fonts: link ONE display font + ONE body font
- Add CSS animations: fade-in on load, hover effects on cards and buttons
- Cards must have box shadows and smooth hover transform
- Smooth scroll behavior on navigation links
- Fully responsive with CSS Grid/Flexbox — works on mobile
- Write REAL content relevant to the prompt, not Lorem ipsum
- Include a mobile hamburger menu that toggles on click
- Make it look like a $5000 professionally designed website"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Build a complete professional website for: {user_prompt}"}
        ],
        temperature=0.7,
        max_tokens=8000,
    )

    html = response.choices[0].message.content.strip()

    # Strip markdown fences if model added them
    if "```" in html:
        parts = html.split("```")
        for part in parts:
            p = part.strip()
            if p.startswith("html"): p = p[4:].strip()
            if p.lower().startswith("<!doctype") or p.startswith("<html"):
                html = p
                break

    # Ensure it starts with doctype
    if not html.lower().startswith("<!doctype") and "<html" not in html[:50]:
        html = "<!DOCTYPE html>\n<html lang='en'>\n" + html + "\n</html>"

    return html


# ═════════════════════════════════════════════════════════
# FLASK ROUTES
# ═════════════════════════════════════════════════════════

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/generate", methods=["POST"])
def generate_ppt():
    data = request.get_json()
    prompt = data.get("prompt", "").strip()
    num_slides = int(data.get("num_slides", 12))
    if not prompt:
        return jsonify({"error": "Please enter a topic."}), 400
    if num_slides < 5 or num_slides > 30:
        return jsonify({"error": "Slide count must be between 5 and 30."}), 400
    try:
        slides_data = generate_slide_content(prompt, num_slides)
        pptx_bytes = build_pptx(slides_data)
        filename = prompt[:35].replace(" ", "_") + ".pptx"
        return send_file(io.BytesIO(pptx_bytes),
            mimetype="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            as_attachment=True, download_name=filename)
    except json.JSONDecodeError:
        return jsonify({"error": "AI returned bad data. Try again."}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/generate-website", methods=["POST"])
def generate_website():
    data = request.get_json()
    prompt = data.get("prompt", "").strip()
    if not prompt:
        return jsonify({"error": "Please enter a website description."}), 400
    try:
        html_code = generate_website_code(prompt)
        site_id = str(uuid.uuid4())[:8]
        filename = f"site_{site_id}.html"
        filepath = os.path.join(SITES_FOLDER, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_code)
        return jsonify({
            "success": True,
            "preview_url": f"/preview/{filename}",
            "download_url": f"/download-site/{filename}",
            "filename": filename
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/preview/<filename>")
def preview_site(filename):
    return send_from_directory(SITES_FOLDER, filename)

@app.route("/download-site/<filename>")
def download_site(filename):
    return send_from_directory(SITES_FOLDER, filename,
        as_attachment=True, download_name=filename.replace("site_","website_"))

if __name__ == "__main__":
    print("\n PPTFinders AI — PPT + Website Generator")
    print(" Open: http://127.0.0.1:5000\n")
    app.run(debug=True)